---
name: Get package semver version
description: 'Get package semver version'
runs:
  using: 'composite'
  steps:
    - name: Set Package SemVer Version on Env
      run: |
        # SEMVER_VERSION=$(npx find-versions-cli ${{ github.event.release.tag_name }})
        SEMVER_VERSION=0.0.2
        VALID_SEMVER_VERSION=$(node scripts/version-helper.js $SEMVER_VERSION)
        echo "Semver stable version unclean $SEMVER_VERSION"
        echo "Semver stable version valid $VALID_SEMVER_VERSION"
        echo "VALID_SEMVER_VERSION=$(echo $VALID_SEMVER_VERSION)" >> $GITHUB_ENV
      shell: bash
