---
name: Publish latest version to Registry
description: 'Publish latest package to registry'
runs:
  using: 'composite'
  steps:
    # - name: Set the Env
    #   run: |
    #     # SEMVER_VERSION=$(npx find-versions-cli ${{ github.event.release.tag_name }})
    #     SEMVER_VERSION=0.0.2
    #     VALID_SEMVER_VERSION=$(node scripts/version-helper.js $SEMVER_VERSION)
    #     echo "Semver stable version unclean $SEMVER_VERSION"
    #     echo "Semver stable version valid $VALID_SEMVER_VERSION"
    #     echo "VALID_SEMVER_VERSION=$(echo $VALID_SEMVER_VERSION)" >> $GITHUB_ENV
    #   shell: bash

    - name: Publish latest to registry
      # if: |
      #   ${{ github.actor != 'dependabot[bot]' }} &&
      #   github.event.release.target_commitish == 'main' &&
      #   startsWith(github.ref, 'refs/tags/v') &&
      #   github.event.release.prerelease == false
      if: |
        ${{ github.actor != 'dependabot[bot]' }} &&
        github.event.release.target_commitish == 'feat-npm-and-github-package-publishing' &&
        github.event.release.prerelease == false
      run: |
        npm publish --dry-run --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
      shell: bash

    - name: Publish next to registry
      # if: |
      #   ${{ github.actor != 'dependabot[bot]' }} &&
      #   github.event.release.target_commitish != 'main' &&
      #   startsWith(github.ref, 'refs/tags/v') &&
      #   github.event.release.prerelease == true
      if: |
        github.event.release.target_commitish != 'main' &&
        ${{ github.actor != 'dependabot[bot]' }}
      run: |
        npm publish --tag next --dry-run --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
      shell: bash
