---
name: Get stable (LATEST) package semver version
description: 'Get stable (LATEST) package semver version'
runs:
  using: 'composite'
  steps:
    - name: Set stable (LATEST) Package SemVer Version on Env
      run: |
        SEMVER_VERSION=$(npx find-versions-cli v0.5.5-test123)
        VALID_SEMVER_VERSION=$(node scripts/version-helper.js $SEMVER_VERSION)
        echo "Semver stable version unclean $SEMVER_VERSION"
        echo "Semver stable version valid $VALID_SEMVER_VERSION"
        echo "VALID_SEMVER_VERSION=$(echo $VALID_SEMVER_VERSION)" >> $GITHUB_ENV
      shell: bash
