---
name: 'Bundle GitHub Page'
description: 'This action bundles the current gh-page branch with the out folder'
runs:
  using: 'composite'
  steps:
    - name: ↔ Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: 🔨 Build page
      env:
        RELEASE: ${{ env.RELEASE }}
        VALID_SEMVER_VERSION: ${{ env.VALID_SEMVER_VERSION }}
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
      run: |
        chmod +rx ./.github/scripts/build-gh-page.sh
        ./.github/scripts/build-gh-page.sh
      shell: bash
