---
name: Publish next version to Registry
description: 'Publish next package to registry'
runs:
  using: 'composite'
  steps:
    - name: Publish to registry
      run: |
        npm publish --tag next --dry-run --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
      shell: bash
