---
name: Init Workflow

on:
  workflow_call:
    inputs:
      prerelease:
        description: 'Is this a Pre-Release?'
        required: true
        type: boolean
      release:
        description: 'Is this a Release?'
        required: true
        type: boolean

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: |
          echo "prerelease?: ${{ inputs.prerelease }}"
          echo "release?: ${{ inputs.release }}"

      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache
        id: 'npm-cache' # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: 📥 Download deps default-npm-cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts
