---
name: Init Workflow

on:
  workflow_call:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache
        id: 'npm-cache' # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: 📥 Download deps default-npm-cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts

      - name: 💾  Save version in .env
        run: echo "VERSION=$(echo 1234)" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.VERSION }}

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
