---
name: Build Stencil Targets

on:
  workflow_call:

jobs:
  build-stencil-targets:
    name: Build Stencil Targets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets: [ngx-elements, react-elements, v-elements]
        # TODO: Use theme if we want to deploy different themes (at the moment local===enterprise===default)
        # TODO: replace local with default theme
        themes: [local, enterprise]
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      # - name: Rename packages
      #   if: ${{ matrix.themes == 'enterprise' }}
      #   run: |
      #     echo "gonna rename here"
      #     npm pkg set 'name'='@db-ui/elements-${{ matrix.themes }}' --workspace=@db-ui/elements
      #     npm pkg set 'name'='@db-ui/ngx-elements-${{ matrix.themes }}' --workspace=@db-ui/ngx-elements
      #     npm pkg set 'name'='@db-ui/react-elements-${{ matrix.themes }}' --workspace=@db-ui/react-elements
      #     npm pkg set 'name'='@db-ui/v-elements-${{ matrix.themes }}' --workspace=@db-ui/v-elements

      #     echo "rename angular specifics"
      #     npx -y replace-in-file @db-ui/elements @db-ui/elements-enterprise packages/db-ui-elements-angular/projects/lib/src/db-ui-elements-module.ts,packages/db-ui-elements-angular/projects/lib/src/components.ts

      #     # npm run build.${{ matrix.themes }} --workspace=@db-ui/elements-${{ matrix.themes }}
      #     cat ./packages/db-ui-elements-stencil/package.json
      #     # npm run build.enterprise --workspace=@db-ui/elements-enterprise

      # - name: 🔨 Build Stencil ${{ matrix.themes }}
      #   if: ${{ matrix.themes == 'enterprise' }}
      #   run: |
      #     npm run build.${{ matrix.themes }} --workspace=@db-ui/elements

      - name: 🔨 Build Stencil ${{ matrix.themes }}
        # if: ${{ matrix.themes == 'local' }}
        run: npm run build.local --workspace=@db-ui/elements

      - name: 🔨 Build Output Targets ${{ matrix.themes }}
        # if: ${{ matrix.themes == 'enterprise' }}
        run: |
          npm run build --workspace=@db-ui/${{ matrix.targets }}
          cat ./packages/db-ui-elements-stencil/package.json

      # - name: 🔨 Build Output Targets ${{ matrix.themes }}
      #   if: ${{ matrix.themes == 'local' }}
      #   run: |
      #     cat ./packages/db-ui-elements-stencil/package.json
      #     npm run build --workspace=@db-ui/${{ matrix.targets }}

      - name: ↔ Get path for target
        run: |
          if echo ${{ matrix.targets }} | grep -c "ngx-elements"
          then
            echo '::set-output name=framework::angular'
          elif echo ${{ matrix.targets }} | grep -c "react-elements"
          then
            echo '::set-output name=framework::react'
          else
            echo '::set-output name=framework::vue'
          fi
        id: path

      - name: Rename packages
        if: ${{ matrix.themes == 'enterprise' }}
        run: |
          echo "rename enterprise packages"
          npm pkg set 'name'='@db-ui/elements-${{ matrix.themes }}' --workspace=@db-ui/elements
          npm pkg set 'name'='@db-ui/ngx-elements-${{ matrix.themes }}' --workspace=@db-ui/ngx-elements
          npm pkg set 'name'='@db-ui/react-elements-${{ matrix.themes }}' --workspace=@db-ui/react-elements
          npm pkg set 'name'='@db-ui/v-elements-${{ matrix.themes }}' --workspace=@db-ui/v-elements
          echo "rename angular specifics"
          npx -y replace-in-file @db-ui/elements @db-ui/elements-enterprise packages/db-ui-elements-angular/projects/lib/src/db-ui-elements-module.ts,packages/db-ui-elements-angular/projects/lib/src/components.ts

      - name: ⬆ Upload Stencil ${{ matrix.themes }}
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: stencil-${{ matrix.themes }}-${{ steps.path.outputs.framework }}
          path: packages/db-ui-elements-stencil

      - name: ⬆ Upload Output Target ${{ steps.path.outputs.framework }}
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: output-target-${{ matrix.themes }}-${{ steps.path.outputs.framework }}
          path: packages/db-ui-elements-${{ steps.path.outputs.framework }}
