---
name: Get and save publish version

on:
  workflow_call:

jobs:
  publish:
    name: Get and save publish version
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 💃🕺 Check if release or prerelease
        run: |
          chmod +rx ./.github/scripts/get-release.sh
          OUTPUT=$(./.github/scripts/get-release.sh)
          echo "$OUTPUT" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_COMMITISH: ${{ github.event.release.target_commitish }}
          GITHUB_RELEASE: ${{ github.event.release.release }}
          GITHUB_PRE_RELEASE: ${{ github.event.release.prerelease }}

      - name: 🏷 Get and Set Package Version on Env
        env:
          RELEASE: ${{ env.RELEASE }}
          PRE_RELEASE: ${{ env.PRE_RELEASE }}
        run: |
          chmod +rx ./.github/scripts/package-version.sh
          OUTPUT=$(./.github/scripts/package-version.sh)
          echo "VALID_SEMVER_VERSION=$(echo OUTPUT)" >> $GITHUB_ENV

      - name: 🌳 Log Valid Version
        env:
          VALID_SEMVER_VERSION: ${{ env.VALID_SEMVER_VERSION }}
        run: echo "$VALID_SEMVER_VERSION"
