---
name: Get and save publish version

on:
  workflow_call:

jobs:
  publish:
    name: Get and save publish version
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 💃🕺 Check if release or prerelease
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/v') }}
          then
            if ${{ github.actor != 'dependabot[bot]' }}
            then
              if ${{ github.event.release.target_commitish == 'main' && github.event.release.release == true }}
              then
                echo "RELEASE=true" >> $GITHUB_ENV
              elif ${{ github.event.release.prerelease == true }}
              then
                echo "PRE_RELEASE=true" >> $GITHUB_ENV
              fi
            else
              echo "Dependabot has no permission to publish!"
              exit 1
            fi
          else
            echo "Your tag has to start with 'v-'"
            exit 1
          fi

      - name: 🏷 Get and Set Package Version on Env
        run: |
          if ${{ env.RELEASE == 'true' }}
          then
            SEMVER_VERSION=$(npx find-versions-cli v0.5.5-test123)
            VALID_SEMVER_VERSION=$(node scripts/version-helper.js $SEMVER_VERSION)
          elif ${{ env.PRE_RELEASE == 'true' }}
          then
            GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
            SEMVER_VERSION=$(npx find-versions-cli v0.5.5-test123)
            VALID_SEMVER_VERSION=$(echo $SEMVER_VERSION-$GITHUB_SHA_SHORT)
          el
            echo "Error: nothing found in environment for REALEASE or PRE_RELEASE"
            exit 1
          fi
          echo "Semver version $VALID_SEMVER_VERSION"
          echo "VALID_SEMVER_VERSION=$(echo $VALID_SEMVER_VERSION)" >> $GITHUB_ENV
          echo "VALID_SEMVER_VERSION saved in environments: ${{ env.VALID_SEMVER_VERSION }}"
