---
name: Get and save publish version

on:
  workflow_call:

jobs:
  publish:
    name: Get and save publish version
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 💃🕺 Set release or prerelease
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/v') }}
          then
            if ${{ github.actor != 'dependabot[bot]' }}
            then
              if ${{ github.event.release.target_commitish == 'main' && github.event.release.release == true }}
              then
                echo "RELEASE=true" >> $GITHUB_ENV
              elif ${{ github.event.release.prerelease == true }}
              then
                echo "PRE_RELEASE=true" >> $GITHUB_ENV
              fi
            fi
          fi

      - name: 🛑 Exit if release or prerelease is not set
        if: ${{ env.RELEASE != 'true' ||  env.PRE_RELEASE != 'true' }}
        run: exit 1

      - name: 🏷 Get and Set Package Version on Env
        run: |
          if ${{ env.RELEASE == 'true' }}
          then
            SEMVER_VERSION=$(npx find-versions-cli v0.5.5-test123)
            VALID_SEMVER_VERSION=$(node scripts/version-helper.js $SEMVER_VERSION)
          elif ${{ env.PRE_RELEASE == 'true' }}
          then
            GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
            SEMVER_VERSION=$(npx find-versions-cli v0.5.5-test123)
            VALID_SEMVER_VERSION=$(echo $SEMVER_VERSION-$GITHUB_SHA_SHORT)
          fi
          echo "Semver version $VALID_SEMVER_VERSION"
          echo "VALID_SEMVER_VERSION=$(echo $VALID_SEMVER_VERSION)" >> $GITHUB_ENV

      - name: 🛑 Exit if VALID_SEMVER_VERSION is not set
        if: ${{ env.VALID_SEMVER_VERSION == "" }}
        run: exit 1
