---
name: Deploy to gh-pages

on:
  workflow_call:
    inputs:
      release:
        required: false
        type: string
      version:
        required: false
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download build
        uses: ./.github/actions/download-tar-artifact
        with:
          name: build
          path: out

      - name: ↔ Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: 🔨 Build page
        env:
          RELEASE: ${{ inputs.release }}
          VALID_SEMVER_VERSION: ${{ inputs.version }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          chmod +rx ./.github/scripts/build-gh-page.sh
          ./.github/scripts/build-gh-page.sh

      - name: 🥅 Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: 🖨️ Print gh-pages url
        env:
          RELEASE: ${{ inputs.release }}
          VALID_SEMVER_VERSION: ${{ inputs.version }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          if [ $RELEASE == "true" ]
          then
            export URL=https://db-ui.github.io/elements
          elif [ -n $VALID_SEMVER_VERSION ];
          then
            export URL=https://db-ui.github.io/elements/version/$VALID_SEMVER_VERSION
          else
            export URL=https://db-ui.github.io/elements/review/${BRANCH}
          fi
          echo "URL: $URL"
          echo "### GH-Pages URL :rocket: <br> <br> $URL" >> $GITHUB_STEP_SUMMARY
