---
name: Publish NPM Package

on:
  workflow_call:

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - {
              DBUI_WORKSPACE: 'elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-stencil',
              DBUI_ARTIFACTNAME: 'stencil-local-angular',
              MY_SECRET: '${{ secrets.secret_input }}'
            }
          - {
              DBUI_WORKSPACE: 'ngx-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-angular',
              DBUI_ARTIFACTNAME: 'output-target-local-angular'
            }
          - {
              DBUI_WORKSPACE: 'react-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-react',
              DBUI_ARTIFACTNAME: 'output-target-local-react'
            }
          - {
              DBUI_WORKSPACE: 'v-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-vue',
              DBUI_ARTIFACTNAME: 'output-target-local-vue'
            }
    env: ${{ matrix.env }}
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download local package build artifacts
        uses: ./.github/actions/download-tar-artifact
        with:
          name: ${{ env.DBUI_ARTIFACTNAME}}
          path: packages/${{ env.DBUI_PACKAGEPATH}}

      - name: Authenticate with Registry
        run: |
          npm logout
          touch .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          cat .npmrc
        env:
          NPM_TOKEN: ${{ env.MY_SECRET }}

      - name: 📰 Publish to NPM (dry run)
        run: |
          GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          # SEMVER_VERSION=$(npx find-versions-cli ${{ github.event.release.tag_name }})
          SEMVER_VERSION=0.0.1-exp
          echo "Semver experimental version $SEMVER_VERSION-$GITHUB_SHA_SHORT"

          npm version --no-git-tag-version $SEMVER_VERSION-$GITHUB_SHA_SHORT --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
          npm publish --dry-run --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
