---
name: Publish all Packages to Registries

on:
  workflow_call:

jobs:
  publish:
    name: Publish latest package versions to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        themes: [default, enterprise]
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download Stencil ${{ matrix.themes }}
        uses: ./.github/actions/download-tar-artifact
        with:
          # As "stencil" package we use the artifact "stencil-default-angular" - others
          # would work as well this is just the first
          name: stencil-${{ matrix.themes }}-angular
          path: packages/db-ui-elements-stencil

      - name: ⬇ Download Output Target Angular ${{ matrix.themes }}
        uses: ./.github/actions/download-tar-artifact
        with:
          name: output-target-${{ matrix.themes }}-angular
          path: packages/db-ui-elements-angular

      - name: ⬇ Download Output Target React ${{ matrix.themes }}
        uses: ./.github/actions/download-tar-artifact
        with:
          name: output-target-${{ matrix.themes }}-react
          path: packages/db-ui-elements-react

      - name: ⬇ Download Output Target Vue ${{ matrix.themes }}
        uses: ./.github/actions/download-tar-artifact
        with:
          name: output-target-${{ matrix.themes }}-vue
          path: packages/db-ui-elements-vue

      - name: 📰 Publish to NPM Registries
        run: |
          chmod +rx ./.github/scripts/publish-npm.sh
          ./.github/scripts/publish-npm.sh
        env:
          RELEASE: ${{ env.RELEASE }}
          PRE_RELEASE: ${{ env.PRE_RELEASE }}
          VALID_SEMVER_VERSION: ${{ env.VALID_SEMVER_VERSION }}
          DBUI_THEME: ${{ matrix.themes }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
