---
name: Publish all Packages to Registries

on:
  workflow_call:
    inputs:
      prerelease:
        description: 'Is this a Pre-Release?'
        required: true
        type: string
      release:
        description: 'Is this a Release?'
        required: true
        type: string

jobs:
  publish:
    name: Publish latest package versions to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # As "stencil" package we use the artifact "stencil-local-angular" - others
      # would work as well this is just the first
      matrix:
        env:
          - {
              DBUI_WORKSPACE: 'elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-stencil',
              DBUI_ARTIFACTNAME: 'stencil-default-angular',
              DBUI_THEME: 'default',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
          - {
              DBUI_WORKSPACE: 'ngx-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-angular',
              DBUI_ARTIFACTNAME: 'output-target-default-angular',
              DBUI_THEME: 'default',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
          - {
              DBUI_WORKSPACE: 'react-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-react',
              DBUI_ARTIFACTNAME: 'output-target-default-react',
              DBUI_THEME: 'default',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
          - {
              DBUI_WORKSPACE: 'v-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-vue',
              DBUI_ARTIFACTNAME: 'output-target-default-vue',
              DBUI_THEME: 'default',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
          - {
              DBUI_WORKSPACE: 'elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-stencil',
              DBUI_ARTIFACTNAME: 'stencil-enterprise-angular',
              DBUI_THEME: 'enterprise',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
          - {
              DBUI_WORKSPACE: 'ngx-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-angular',
              DBUI_ARTIFACTNAME: 'output-target-enterprise-angular',
              DBUI_THEME: 'enterprise',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
          - {
              DBUI_WORKSPACE: 'react-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-react',
              DBUI_ARTIFACTNAME: 'output-target-enterprise-react',
              DBUI_THEME: 'enterprise',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
          - {
              DBUI_WORKSPACE: 'v-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-vue',
              DBUI_ARTIFACTNAME: 'output-target-enterprise-vue',
              DBUI_THEME: 'enterprise',
              DBUI_TEST: ${{ inputs.prerelease }}
            }
        registries: [npm, github]
    env: ${{ matrix.env }}
    steps:
      - name: TEST
        run: |
          echo "prerelease?: ${{ inputs.prerelease }}"
          echo "release?: ${{ inputs.release }}"
          echo  "env is?: ${{ env.DBUI_TEST }}"

      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download local package build artifacts
        uses: ./.github/actions/download-tar-artifact
        with:
          name: ${{ env.DBUI_ARTIFACTNAME}}
          path: packages/${{ env.DBUI_PACKAGEPATH}}

      - name: 🏷 Get and Set stable (LATEST) Package Version on Env
        if: ${{ inputs.release == true }}
        uses: ./.github/actions/get-package-version-latest

      - name: 🏷 Get and Set experimental (NEXT) Package Version on Env
        if: ${{ inputs.prerelease == true }}
        uses: ./.github/actions/get-package-version-next

      - name: 🛠 Forge enterprise packages
        if: ${{ env.DBUI_THEME == 'enterprise' }}
        #   run: |
        #     echo "which packages?: ${{ inputs.registry }}"
        #     echo "which verison ?: ${{ env.VALID_SEMVER_VERSION }}"
        #     echo "TODO: forge enterprise versions..."
        #     # npm pkg set 'name'='@db-ui/elements-${{ matrix.themes }}' --workspace=@db-ui/elements
        #     # npx -y replace-in-file @db-ui/elements @db-ui/elements-enterprise packages/**/dist/**/*.*
        #     # npm pkg set 'dependencies.@db-ui-elements-enterprise'='1.1.1' --workspace=@db-ui/ngx-elements
        run: |
          echo "Forge enterprise versions..."
          echo "which verison ?: ${{ env.VALID_SEMVER_VERSION }}"
          # npx -y replace-in-file @db-ui/elements @db-ui/elements-enterprise packages/**/dist/**/*.*
          # npm pkg set 'dependencies.@db-ui-elements-enterprise'='1.1.1' --workspace=@db-ui/ngx-elements
          # npx -y replace-in-file @db-ui/elements @db-ui/elements-enterprise packages/**/dist/**/*.*
          npm version --no-git-tag-version ${{ env.VALID_SEMVER_VERSION }} --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
          npm pkg set 'dependencies.@db-ui/elements'='${{ env.VALID_SEMVER_VERSION }}' --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
          npm pkg set 'name'='@db-ui/elements-${{ env.DBUI_WORKSPACE }}-${{ env.DBUI_WORKSPACE }}-${{ env.DBUI_THEME}}' --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
          cat packages/${{ env.DBUI_PACKAGEPATH }}/package.json

      - name: 🛠 Forge default packages
        if: ${{ env.DBUI_THEME == 'default' }}
        run: |
          echo "Forge default versions..."
          echo "which verison ?: ${{ env.VALID_SEMVER_VERSION }}"
          npm version --no-git-tag-version ${{ env.VALID_SEMVER_VERSION }} --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
          npm pkg set 'dependencies.@db-ui/elements'='${{ env.VALID_SEMVER_VERSION }}' --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}
          cat packages/${{ env.DBUI_PACKAGEPATH }}/package.json

      - name: Authenticate with NPM Registry
        if: ${{ matrix.registries == 'npm'}}
        uses: ./.github/actions/auth-with-registry
        with:
          registry: '//npm.pkg.github.com/'
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TEST_TOKEN}}

      - name: Authenticate with GitHub Registry
        uses: ./.github/actions/auth-with-registry
        if: ${{ matrix.registries == 'github'}}
        with:
          registry: '//npm.pkg.github.com/'
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TEST_TOKEN}}

      - name: 📰 Publish to Package Registry (dry run)
        uses: ./.github/actions/publish-to-registry
        env:
          DBUI_WORKSPACE: ${{ env.DBUI_WORKSPACE }}
