---
name: Publish all Packages to Registries

on:
  workflow_call:

jobs:
  publish:
    name: Publish latest package versions to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # As "stencil" package we use the artifact "stencil-default-angular" - others
      # would work as well this is just the first
      matrix:
        env:
          - {
              DBUI_WORKSPACE: 'elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-stencil',
              DBUI_ARTIFACTNAME: 'stencil-default-angular',
              DBUI_THEME: 'default'
            }
          - {
              DBUI_WORKSPACE: 'ngx-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-angular',
              DBUI_ARTIFACTNAME: 'output-target-default-angular',
              DBUI_THEME: 'default'
            }
          - {
              DBUI_WORKSPACE: 'react-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-react',
              DBUI_ARTIFACTNAME: 'output-target-default-react',
              DBUI_THEME: 'default'
            }
          - {
              DBUI_WORKSPACE: 'v-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-vue',
              DBUI_ARTIFACTNAME: 'output-target-default-vue',
              DBUI_THEME: 'default'
            }
          - {
              DBUI_WORKSPACE: 'elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-stencil',
              DBUI_ARTIFACTNAME: 'stencil-enterprise-angular',
              DBUI_THEME: 'enterprise'
            }
          - {
              DBUI_WORKSPACE: 'ngx-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-angular',
              DBUI_ARTIFACTNAME: 'output-target-enterprise-angular',
              DBUI_THEME: 'enterprise'
            }
          - {
              DBUI_WORKSPACE: 'react-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-react',
              DBUI_ARTIFACTNAME: 'output-target-enterprise-react',
              DBUI_THEME: 'enterprise'
            }
          - {
              DBUI_WORKSPACE: 'v-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-vue',
              DBUI_ARTIFACTNAME: 'output-target-enterprise-vue',
              DBUI_THEME: 'enterprise'
            }
        registries: [npm, github]
    env: ${{ matrix.env }}
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download local package build artifacts
        uses: ./.github/actions/download-tar-artifact
        with:
          name: ${{ env.DBUI_ARTIFACTNAME}}
          path: packages/${{ env.DBUI_PACKAGEPATH}}

      - name: 🛠 Forge all packages version numbers
        run: |
          echo "Forge all packages..."
          echo "which package verison ?: ${{ env.VALID_SEMVER_VERSION }}"
          npm version --no-git-tag-version ${{ env.VALID_SEMVER_VERSION }} --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}

      - name: 🛠 Forge enterprise packages
        if: ${{ env.DBUI_THEME == 'enterprise' }}
        run: |
          echo "Forge enterprise string replacement..."
          npx -y replace-in-file @db-ui/elements @db-ui/elements-enterprise 'packages/**/dist/**/*.*'

      - name: 🛠 Forge default output target packages dependency
        if: ${{ env.DBUI_THEME == 'default' && env.DBUI_WORKSPACE != 'elements' }}
        run: |
          echo "Forge default output target packages dependency..."
          echo "which verison ?: ${{ env.VALID_SEMVER_VERSION }}"
          npm pkg set 'dependencies.@db-ui/elements'='${{ env.VALID_SEMVER_VERSION }}' --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}

      - name: 🛠 Forge enterprise output target packages dependency
        if: ${{ env.DBUI_THEME == 'enterprise' && env.DBUI_WORKSPACE != 'enterprise' }}
        run: |
          echo "Forge enterprise output target packages dependency..."
          echo "which verison ?: ${{ env.VALID_SEMVER_VERSION }}"
          npm pkg set 'dependencies.@db-ui/elements-enterprise'='${{ env.VALID_SEMVER_VERSION }}' --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}

      - name: 🛠 Forge enterprise packages name
        if: ${{ env.DBUI_THEME == 'enterprise' }}
        run: |
          echo "Forge enterprise package name..."
          npm pkg set 'name'='@db-ui/${{ env.DBUI_WORKSPACE }}-${{ env.DBUI_THEME}}' --workspace=@db-ui/${{ env.DBUI_WORKSPACE }}

      - name: 🔑 Authenticate with NPM Registry
        if: ${{ matrix.registries == 'npm'}}
        uses: ./.github/actions/auth-with-registry
        with:
          registry: '//registry.npmjs.org/'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🔑 Authenticate with GitHub Registry
        uses: ./.github/actions/auth-with-registry
        if: ${{ matrix.registries == 'github'}}
        with:
          registry: '//npm.pkg.github.com/'
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📰 Publish Package to Registry (dry run)
        run: |
          if ${{ env.DBUI_THEME == 'default' }}
          then
            PACKAGE_NAME = $(echo ${{ env.DBUI_WORKSPACE }})
          else
            PACKAGE_NAME = $(echo ${{ env.DBUI_WORKSPACE }}-${{ env.DBUI_THEME }})
          fi

          if ${{ env.RELEASE == 'true' }}
          then
            npm publish --dry-run --workspace=@db-ui/$PACKAGE_NAME
          else if ${{ env.PRE_RELEASE == 'true' }}
            npm publish --tag next --dry-run --workspace=@db-ui/$PACKAGE_NAME
          fi

          echo "Pack tarball"
          npm pack --workspace=@db-ui/$PACKAGE_NAME

      - name: ⬆ Upload Package Artifact ${{ matrix.registries }}-${{ env.DBUI_ARTIFACTNAME }}
        if: ${{ env.DBUI_THEME == 'default' }}
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: package-${{ matrix.registries }}-${{ env.DBUI_ARTIFACTNAME }}
          path: db-ui-${{ env.DBUI_WORKSPACE }}-${{ env.VALID_SEMVER_VERSION }}.tgz

      - name: ⬆ Upload Package Artifact ${{ matrix.registries }}-${{ env.DBUI_ARTIFACTNAME }}
        if: ${{ env.DBUI_THEME == 'enterprise' }}
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: package-${{ matrix.registries }}-${{ env.DBUI_ARTIFACTNAME }}
          path: db-ui-${{ env.DBUI_WORKSPACE }}-${{ env.DBUI_THEME }}-${{ env.VALID_SEMVER_VERSION }}.tgz
