name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    name: Unit/Snapshot Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Run unit/snapshot tests
        run: |
          npm test

  cypress:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 👩‍🍳 Bake everything (StoryBook, Playground & Showcases)
        run: |
          npm run build
          node scripts/build angular,react,vue,playground,reactwind withShowcase
          npm run build:storybook

      - name: 🧪 Cypress run
        # Install NPM dependencies and run all Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npx http-server@14.1.1 public
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080

      - name: 🛗 Upload Artifacts
        uses: actions/upload-artifact@v2
        # after the test run completes
        # store videos and any screenshots
        # NOTE: screenshots will be generated only if an E2E test failed
        # thus we store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots
      - uses: actions/upload-artifact@v2
        # Test run video was always captured, so this action uses "always()" condition
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [test, cypress]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 👩‍🍳 Bake everything (StoryBook, Playground & Showcases)
        run: |
          npm run build
          node scripts/build angular,react,vue,playground,reactwind withShowcase
          npm run build:storybook

      - name: 🛗 Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: storybook-page
          path: public

      - name: 📖 Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
