---
name: Test and publish to registries after new tag

on:
  push:
    branches:
      - feat-npm-and-github-package-publishing

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  scan-secrets:
    uses: ./.github/workflows/00-scan-secrets.yml

  test:
    uses: ./.github/workflows/01-test.yml
    needs: [init]

  validate:
    uses: ./.github/workflows/01-validate.yml
    needs: [init]

  build-stencil-targets:
    uses: ./.github/workflows/01-build-stencil-targets.yml
    needs: [init]

  # build-showcases:
  #   uses: ./.github/workflows/01-build-showcases.yml
  #   needs: [build-stencil-targets]

  # build-storybook:
  #   uses: ./.github/workflows/01-build-storybook.yml
  #   needs: [build-showcases]

  # cypress:
  #   uses: ./.github/workflows/02-cypress.yml
  #   needs: [build-storybook]

  # release:
  #   uses: ./.github/workflows/03-gh-release.yml
  #   if: ${{ github.actor != 'dependabot[bot]' }}
  #   needs: [validate, test, cypress]

  publishpackages:
    uses: ./.github/workflows/03-npm-publish.yml
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - {
              DBUI_WORKSPACE: 'elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-stencil',
              # It doesn't matter which framework we download for stencil
              DBUI_ARTIFACTNAME: 'stencil-local-angular'
            }
          - {
              DBUI_WORKSPACE: 'ngx-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-angular',
              DBUI_ARTIFACTNAME: 'output-target-local-angular'
            }
          - {
              DBUI_WORKSPACE: 'react-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-react',
              DBUI_ARTIFACTNAME: 'output-target-local-react'
            }
          - {
              DBUI_WORKSPACE: 'v-elements',
              DBUI_PACKAGEPATH: 'db-ui-elements-vue',
              DBUI_ARTIFACTNAME: 'output-target-local-vue'
            }
    env: ${{ matrix.env }}
    # needs: [validate, test, cypress]
    needs: [build-stencil-targets, validate, test]
