---
name: Test and publish to package registries after new GitHug release

on:
  release:
    types: [published]

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  scan-secrets:
    uses: ./.github/workflows/00-scan-secrets.yml

  test:
    uses: ./.github/workflows/01-test.yml
    needs: [init]

  validate:
    uses: ./.github/workflows/01-validate.yml
    needs: [init]

  build-stencil-targets:
    uses: ./.github/workflows/01-build-stencil-targets.yml
    needs: [init]

  build-showcases:
    uses: ./.github/workflows/01-build-showcases.yml
    needs: [build-stencil-targets]

  build-storybook:
    uses: ./.github/workflows/01-build-storybook.yml
    needs: [build-showcases]

  cypress:
    uses: ./.github/workflows/02-cypress.yml
    needs: [build-storybook]

  publishpackages:
    uses: ./.github/workflows/03-publish-packages.yml
    needs: [validate, test, cypress]
    with:
      prerelease: ${{ github.event.release.target_commitish != 'main' && startsWith(github.ref, 'refs/tags/v') && github.event.release.prerelease == true && github.actor != 'dependabot[bot]' }}
      release: ${{ github.event.release.target_commitish == 'main' && startsWith(github.ref, 'refs/tags/v') && github.event.release.release == true && github.actor != 'dependabot[bot]' }}

  changeloglatest:
    uses: ./.github/workflows/changelog.yml
    needs: [publishpackages]
